apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: jenkins-leader-pvc 
  namespace: ns-jenkins
spec: 
  accessModes: 
    - ReadWriteMany
  resources: 
    requests: 
      storage: 500Mi
